### ISSUE TITLE
Add US-ASCII support

### ISSUE THREAD

**Issue by sylv256** [nneonneo/firefox-charset-extension#1]
would be cool to have US-ASCII support

**Comment by nneonneo** [comment]
US-ASCII is a 7-bit code; most of the single-byte encodings such as ISO-8859-* and windows-1252, among others, extend US-ASCII to 8 bits with additional characters.

In particular, on the Web, an encoding of "ASCII" or "US-ASCII" actually resolves to windows-1252, which is one of the supersets of US-ASCII. You can see a full list of supported encodings and their recognized aliases here: https://encoding.spec.whatwg.org/#names-and-labels

So, I think US-ASCII is already supported. Since there are so many aliases, it is not feasible to display them all in the interface; maybe I would need some kind of search + suggest feature for that.

**Comment by nneonneo** [comment]
FWIW, I tried to add a search+suggest feature but it made the UI too big and bulky, so I will not be implementing it anymore.
