### ISSUE TITLE
Feature request: Black colour option for toolbar icon

### ISSUE THREAD

**Issue by Aleksandra0056** [nneonneo/firefox-charset-extension#2]
Hello, I want to request a new feature about manually setting the toolbar icon to be in black colour because the current grey extension icon isn't well visible in my Pink theme especially if I have the Override Text Encoding button placed in the darker pink area (in the third-party status bar, but it has the same colour as the area in tab bar).

I think, that the option should be located on a new options page in about:addons and not in the extension menu because it would create clutter.

Link to a theme I mentioned: https://addons.mozilla.org/en-US/firefox/addon/rosa-pink/

----------

For any response, thanks!

Have a very nice day!

**Comment by Aleksandra0056** [comment]
By the way options for manually setting dark, light or system icon themes would be useful since it is standard in many apps and extensions and it would help users to set the correct option if they have a theme with colours which are wrongly automatically detected. But that's a thing for another issue.

**Comment by nneonneo** [comment]
I would love to! But I'm not really sure how to do it. Are there examples of other addons which do do this, so I can use them as a reference?

**Comment by Aleksandra0056** [comment]
> I would love to! But I'm not really sure how to do it. Are there examples of other addons which do do this, so I can use them as a reference?

Yes, one example is Tabs Aside by Tim-we.

The source code is here: https://github.com/tim-we/tabs-aside

This is the setting which changes the extension to use black colour:
![Screenshot 2024-08-05 022836](https://github.com/user-attachments/assets/637c207a-a368-4e03-93aa-77902643ea29)

If it won't help, then I can find any other extensions doing this.

**Comment by nneonneo** [comment]
That was very helpful, thanks! I've updated the extension and packaged a new version (attached). If you'd like to give it a try before it goes on Mozilla Add-ons (since that process takes a while...), I've attached a copy here.

In order to install it, uninstall the existing extension, go to Addons -> gear icon -> Debug Addons -> Load Temporary Addon. This addon will go away if you restart the browser, but at least it'll allow you to test the new functionality and let me know if it works for you.

[extension.zip](https://github.com/user-attachments/files/16490489/extension.zip)
